//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

// ------- Dynamically Linked Functions Without Header --------

int32_t asprintf(char ** a1, char * a2, ...);
int32_t setresgid(int32_t a1, int32_t a2, int32_t a3);
int32_t setresuid(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// From module:   /home/user/level07/level07.c
// Address range: 0x8048514 - 0x80485a1
// Line range:    6 - 24
int main() {
    int32_t v1 = getegid(); // 0x804851d
    int32_t v2 = geteuid(); // 0x8048526
    setresgid(v1, v1, v1);
    setresuid(v2, v2, v2);
    char * buffer = NULL; // bp-28, 0x8048567
    asprintf(&buffer, "/bin/echo %s ", getenv("LOGNAME"));
    return system(buffer);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.5.x)
// Detected functions: 1

